name: colyseus_flutter
description: colyseus Flutter Sdk
version: 0.0.1
author: junsuk5
homepage: http://github.com/junsuk5/colyseus_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  web_socket_channel: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter